config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :identities
    resources :folders
    resources :notes
    resources :uploads

    root to: 'users#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks',  registrations: 'registrations' }
  get 'welcome/index'
  resources :folders
  resources :notes
  resources :uploads
  resources :charges
  get 'search_results/index', to: 'search_results#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root 'folders#index', as: 'authenticated_root'
  end

  root 'welcome#index'
  get '/prices', to: 'welcome#prices'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]
end

app/models/folder.rb
# frozen_string_literal: true
# Folders hold uploads and notes
class Folder < ActiveRecord::Base
  belongs_to :user
  has_many :uploads
  has_many :notes

  validates_presence_of :user_id, :name
end

app/controllers/folders_controller.rb
# frozen_string_literal: true
# Controller to handle folders
class FoldersController < ApplicationController
  before_action :find_folder, only: [:show, :edit, :update, :destroy]
  before_action :find_parent, only: [:show]
  load_and_authorize_resource

  def index
    @folders = Folder.where(user_id: current_user, parent_folder_id: nil).paginate(page: params[:page], per_page: 4)
    @folders = Folder.search(params[:search]).order('created_at DESC').paginate(page: params[:page], per_page: 4) if params[:search]
  end

  def show
    @folders = Folder.where(user_id: current_user, parent_folder_id: @folder.id)
    @notes = Note.where(user_id: current_user, folder_id: @folder).paginate(page: params[:page], per_page: 4)
    @uploads = Upload.where(user_id: current_user, folder_id: @folder)
  end

  def new
    @folder = current_user.folders.build
  end

  def create
    @folder = current_user.folders.build(folder_params)
    @folder.parent_folder_id = params[:folder][:parent_folder_id]
    if @folder.save
      flash[:notice] = 'Boom! Your Folder successfully saved! 💣'
      redirect_to @folder
    else
      flash[:notice] = 'Hmm... Something went wrong. 🤔'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @folder.update(folder_params)
      flash[:notice] = 'Hot Dog! Your Folder had been updated! 🌭'
      redirect_to root_path
    else
      flash[:notice] = 'Hmm... Something went wrong. 🤔'
      render 'edit'
    end
  end

  def destroy
    @folder.destroy
    flash[:notice] = "✌️ out, #{@folder.name}. No one liked that folder anyway..."
    redirect_to(:back)
  end

  private

  def find_folder
    @folder = Folder.find(params[:id])
  end

  def find_parent
    @parent_folder = Folder.where(user_id: current_user, id: @folder.parent_folder_id)
  end

  def folder_params
    params.require(:folder).permit(:name)
  end
end

app/helpers/folders_helper.rb
# frozen_string_literal: true
# FoldersHelper
module FoldersHelper
  def find_parents(folder)
    @parent_folders ||= {}
    if folder.parent_folder_id.present?
      parent_folder = Folder.find(folder.parent_folder_id)
      @parent_folders[parent_folder.id.to_s] = parent_folder.name
      find_parents(parent_folder)
    end
    @parent_folders.reverse_each.to_h
  end
end

app/views/folders/edit.haml
%h2.bold "Edit #{@folder.name}"
%br
%br
= form_for @folder, html: { multipart: true } do |f|
  = f.label :name
  = f.text_field :name
  %br
  %br
  %br
  = f.submit 'Save', class: 'btn white-text deep-purple accent-3'
%br
%br
%br

app/views/folders/index.html.erb
<% unless @folders.blank? %>
  <br>
  <h3 class="bold deep-purple-text text-accent-3">
    Folders&nbsp&nbsp
    <%= link_to new_folder_path do %>
      <i class='fa fa-plus-circle deep-purple-text text-accent-3 pull-right' style='margin-top:5px;'></i>
    <% end %>
  </h3>
  <hr>
  <div class="section">
    <div class='row'>
      <table class="striped">
        <tr>
          <th>Folder</th>
          <th>Last edit</th>
          <th>Actions</th>
        </tr>
        <% @folders.each do |folder| %>
          <tr>
            <td><%= folder.name %></td>
            <td><%= time_ago_in_words(folder.created_at) %> ago</td>
            <td>
              <a href="<%= (url_for [folder]) %>"><i class='fa fa-lg fa-folder-open-o deep-purple-text text-accent-3'></i></a>
              <%= link_to edit_folder_path(folder) do %>
                  <i class='fa fa-lg fa-pencil-square-o deep-purple-text text-accent-3'></i>
              <% end %>
              <%= link_to folder_path(folder), method: :delete, data: {confirm: 'Are you sure?'} do %>
                <i class='fa fa-lg fa-trash-o deep-purple-text text-accent-3'></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <br>
  <div align="center">
  <%= will_paginate @folders, renderer: MaterializePagination::Rails %>
  </div>
<% else %>
  <br>
  <h3 class="bold">Folders</h3>
  <hr>
  <%= link_to 'New Folder', new_folder_path, class: 'waves-effect btn white-text deep-purple accent-3' %>
<% end %>
<br/><br/><br/>

app/views/folders/new.haml
%h2.bold Add a Folder
%br
%br
= form_for @folder, html: { multipart: true } do |f|
  = f.label :name
  = f.text_field :name
  = f.hidden_field :parent_folder_id, :value => params[:folder_id]
  %br
  %br
  %br
  = f.submit 'Save', class: 'btn white-text deep-purple accent-3'
%br
%br
%br

app/views/folders/show.html.erb
<h3 class="bold deep-purple-text text-accent-3">
  <% unless @parent_folder.blank? %>
    <% find_parents(@folder).each do |parent| %>
      <%= link_to folder_path(parent[0]) do %>
        <%= parent[1] + " > " %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to root_path do %>
      Home >
    <% end %>
  <% end %>
  <%= @folder.name %>
</h3>
<% unless @folders.blank? %>
  <br>
  <h4 class="bold">
    Folders&nbsp&nbsp
    <%= link_to new_folder_path(folder_id: @folder.id) do %>
        <i class='fa fa-plus-circle deep-purple-text text-accent-3 pull-right'></i>
    <% end %>
  </h4>
  <hr>
  <div class="section">
    <div class='row'>
      <table class="striped">
        <tr>
          <th>Folder</th>
          <th>Last edit</th>
          <th>Actions</th>
        </tr>
        <% @folders.each do |folder| %>
          <tr>
            <td><%= folder.name %></td>
            <td><%= time_ago_in_words(folder.created_at) %> ago</td>
            <td>
              <a href="<%= (url_for [folder]) %>"><i class='fa fa-lg fa-folder-open-o deep-purple-text text-accent-3'></i></a>
              <%= link_to edit_folder_path(folder) do %>
                  <i class='fa fa-lg fa-pencil-square-o deep-purple-text text-accent-3'></i>
              <% end %>
              <%= link_to folder_path(folder), method: :delete, data: {confirm: 'Are you sure?'} do %>
                <i class='fa fa-lg fa-trash-o deep-purple-text text-accent-3'></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <br>
<% else %>
  <br>
  <h3 class="bold">Folders</h3>
  <hr>
  <%= link_to 'New Folder', new_folder_path(folder_id: @folder.id), class: 'waves-effect btn white-text deep-purple accent-3' %>
<% end %>
<% unless @notes.blank? %>
  <br>
  <h4 class="bold">
    Notes&nbsp&nbsp
    <%= link_to new_note_path(folder_id: @folder.id) do %>
        <i class='fa fa-plus-circle deep-purple-text text-accent-3 pull-right'></i>
    <% end %>
  </h4>
  <hr>
  <div class="section">
    <div class='row'>
      <table class="striped">
        <tr>
          <th>Note</th>
          <th>Last edit</th>
          <th>Actions</th>
        </tr>
        <% @notes.each do |note| %>
            <tr>
              <td><%= note.title %></td>
              <td><%= time_ago_in_words(note.created_at) %> ago</td>
              <td>
                <%= link_to note_path(note) do %>
                  <i class='fa fa-lg fa-eye deep-purple-text text-accent-3'></i>
                <% end %>
                <%= link_to edit_note_path(note) do %>
                    <i class='fa fa-lg fa-pencil-square-o deep-purple-text text-accent-3'></i>
                <% end %>
                <%= link_to note_path(note), method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class='fa fa-lg fa-trash-o deep-purple-text text-accent-3'></i>
                <% end %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
  <br>
  <div align="center">
  <%= will_paginate @notes, renderer: MaterializePagination::Rails %>
  </div>
  <br>
  <%= render 'uploads/index' %>
<% else %>
  <br>
  <h3 class="bold">Notes</h3>
  <hr>
  <%= link_to 'New Note', new_note_path(folder_id: @folder.id), class: 'waves-effect btn white-text deep-purple accent-3' %>
  <br>
  <br>
  <%= render 'uploads/index' %>
<% end %>
<br/><br/><br/>