config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :identities
    resources :folders
    resources :notes
    resources :uploads

    root to: 'users#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks',  registrations: 'registrations' }
  get 'welcome/index'
  resources :folders
  resources :notes
  resources :uploads
  resources :charges
  get 'search_results/index', to: 'search_results#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root 'folders#index', as: 'authenticated_root'
  end

  root 'welcome#index'
  get '/prices', to: 'welcome#prices'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]
end

app/models/upload.rb
# frozen_string_literal: true
# Uploads model
class Upload < ActiveRecord::Base
  acts_as_paranoid
  mount_uploader :attachment, AttachmentUploader
  belongs_to :user
  belongs_to :folder

  before_save :data_limit_check

  validates_presence_of :name, :user_id, :folder_id, :size

  FREE = 5_000_000_000
  PREMIUM = 10_000_000_000

  def data_limit_check
    size = self.size.to_i
    total_size_after = user.total_data + size
    if user.subscription == 'free'
      false if FREE <= total_size_after
    elsif user.subscription == 'premium'
      false if PREMIUM <= total_size_after
    else
      false
    end
  end
end

app/controllers/admin/uploads_controller.rb
# frozen_string_literal: true
module Admin
  class UploadsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Upload.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Upload.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true
# Controller to handle the files uploaded by users
class UploadsController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @uploads = Upload.all.where(user_id: current_user)
  end

  def new
    @folder = Folder.find(params[:folder_id])
    @upload = current_user.uploads.new
  end

  def create
    @upload = current_user.uploads.new(upload_params)
    @upload.folder_id = params[:folder_id]

    if @upload.save
      total_data
      flash[:notice] = 'Baller! Your file was uploaded! 🏀'
      redirect_to controller: 'folders', action: 'show', id: @upload.folder_id
    else
      flash[:notice] = 'Well, this is awkward... 😬'
      redirect_to(:back)
    end
  end

  def destroy
    @upload = Upload.find(params[:id])
    if @upload.present?
      @upload.destroy
      total_data
      flash[:notice] = '😎 more room for activities!'
    end
    redirect_to(:back)
  end

  private

  def upload_params
    params.require(:upload).permit(:name, :attachment, :content_type, :size, :folder_id)
  end

  def total_data
    total = 0
    uploads = Upload.all.where(user_id: current_user)
    uploads.each do |upload|
      total += upload.size.to_i if upload.present?
    end
    current_user.total_data = total
    current_user.save
  end
end

app/helpers/uploads_helper.rb
# frozen_string_literal: true
# UploadsHelper
module UploadsHelper
end

app/views/uploads/_index.haml
- unless @uploads.blank?
  %br
  %h4.bold
    Files&nbsp&nbsp
    = link_to new_upload_path(folder_id: @folder.id) do
      %i.fa.fa-plus-circle.deep-purple-text.text-accent-3.pull-right
  %hr
  .section
    .row
      %table.striped
        %tr
          %th Name
          %th Size
          %th Last Edit
          %th Actions
        - @uploads.each do |upload|
          %tr
            %td= upload.name
            %td= number_to_human_size(upload.size.to_i)
            %td= "#{time_ago_in_words(upload.created_at)} ago"
            %td
              = link_to upload.attachment_url, target: '_blank' do
                %i.fa.fa-lg.fa-arrow-circle-o-down.deep-purple-text.text-accent-3
              = link_to edit_upload_path(upload) do
                %i.fa.fa-lg.fa-pencil-square-o.deep-purple-text.text-accent-3
              = link_to upload_path(upload), method: :delete, data: {confirm: 'Are you sure?'} do
                %i.fa.fa-lg.fa-trash-o.deep-purple-text.text-accent-3
- else
  %br
  %h4.bold Files
  %hr
  = link_to 'Add File', new_upload_path(folder_id: @folder.id), class: 'waves-effect btn white-text deep-purple accent-3'

app/views/uploads/new.haml
%h2.bold Add a File
%br
%br
= form_for @upload, html: { multipart: true } do |f|
  = f.label :name
  = f.text_field :name
  %br
  %br
  %br
  = hidden_field_tag 'folder_id', @folder.id
  = f.label :attachment
  = f.file_field :attachment
  %br
  %br
  %br
  = f.submit 'Save', class: 'btn white-text deep-purple accent-3'
%br
%br
%br