config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :identities
    resources :folders
    resources :notes
    resources :uploads

    root to: 'users#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks',  registrations: 'registrations' }
  get 'welcome/index'
  resources :folders
  resources :notes
  resources :uploads
  resources :charges
  get 'search_results/index', to: 'search_results#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  authenticated :user do
    root 'folders#index', as: 'authenticated_root'
  end

  root 'welcome#index'
  get '/prices', to: 'welcome#prices'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources 'contacts', only: [:new, :create]
end

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="grey darken-4" role="navigation">
      <div class="nav-wrapper container">
        <%= link_to root_url, class: 'brand-logo white-text bold', id: 'logo-container' do %>
            DevCloud
        <% end %>
        <a href="#" data-activates="mobile-demo" class="button-collapse white-text"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down row">
          <% if current_user.image %>
              <%= form_tag(search_results_index_path, method: 'get', id: 'search-form', class: 'input-field') do %>
                  <li><%= text_field_tag :search, params[:search], placeholder: 'Search Notes...', id: 'search' %></li>
                  <li><%= button_tag 'Search', type: 'submit', class: 'btn deep-purple accent-3 white-text' %></li>
                  <li>
                    <a id="profile-pic" class='button' href='#' data-activates='slide-out'><%= image_tag(current_user.image, class: 'circle responsive-img profile_pic', size: '48x48', alt: current_user.name) %></a>
                  </li>
              <% end %>
          <% else %>
              <%= form_tag(search_results_index_path, method: 'get', id: 'search-form', class: 'input-field') do %>
                  <li><%= text_field_tag :search, params[:search], placeholder: 'Search Notes...', id: 'search' %></li>
                  <li><%= button_tag 'Search', type: 'submit', class: 'btn deep-purple accent-3 white-text' %></li>
                  <li><a class='button' href='#' data-activates='slide-out'><i class="material-icons">menu</i></a></li>
              <% end %>
          <% end %>
        </ul>

        <%= render partial: 'layouts/slideout_menu' %>
        <%= render partial: 'layouts/mobile_menu' %>
      </div>
    </nav>
  </div>
  <script>$(document).ready(function () {
    $('.button-collapse').sideNav();
    $('.button').sideNav({edge: 'right'});
  });
  </script>
</header>

app/views/layouts/_mobile_menu.haml
.center
  %ul.side-nav.grey.darken-4#mobile-demo
    - if user_signed_in?
      - if current_user.image
        %li= image_tag(current_user.image, class: 'circle responsive-img mobile_profile_pic', size: '140x140', alt: current_user.name)
      = form_tag(search_results_index_path, method: 'get', id: 'search-form', class: 'input-field') do
        %li= text_field_tag :search, params[:search], placeholder: 'Search Notes', id: 'search', style: 'width: 50%;'
        %li= button_tag 'Search', type: 'submit', class: 'btn deep-purple accent-3 white-text'
        %li= link_to 'Home', root_url, class: 'white-text'
        %li= link_to 'New Folder', new_folder_path, class: 'white-text'
        %li= link_to 'Settings', edit_user_registration_path, class: 'white-text'
        %li= link_to 'Contact Us', contacts_path, class: 'white-text'
        %li= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'white-text'
    - else
      %li= link_to 'Home', root_url, class: 'btn grey darken-4 white-text'
      %li= link_to 'Contact Us', contacts_path, class: 'btn grey darken-4 white-text'
      %li= link_to 'Sign in', new_user_session_path, class: 'btn deep-purple accent-3 white-text'

app/views/layouts/_slideout_menu.haml
%ul#slide-out.side-nav.center
  - if user_signed_in?
    - if current_user.image
      %li= image_tag(current_user.image, class: 'circle responsive-img mobile_profile_pic', :size => '140x140', alt: current_user.name)
    %li= link_to 'Home', root_url, class: 'btn deep-purple accent-3 white-text'
    %li= link_to 'New Folder', new_folder_path, class: 'btn grey darken-4 white-text'
    %li= link_to 'Settings', edit_user_registration_path, class: 'btn grey darken-4 white-text'
    %li= link_to 'Contact Us', contacts_path, class: 'btn grey darken-4 white-text'
    %li= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn grey darken-4 white-text'
  - else
    %li= link_to 'Home', root_url, class: 'btn grey darken-4 white-text'
    %li= link_to 'Contact Us', contacts_path, class: 'btn grey darken-4 white-text'
    %li= link_to 'Sign in', new_user_session_path, class: 'btn deep-purple accent-3 white-text'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevCloud</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

  <%= javascript_include_tag :application %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>

  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= render 'layouts/header' %>
<% end %>
<main>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= javascript_tag "Materialize.toast('#{message}', 3000)" %>
    <% end %>
    <%= yield %>
  </div>
</main>
</body>
</html>

app/views/layouts/charges.haml
= yield